#!/bin/sh
# sync-instructions.sh — Regenerate agent instruction files from the canonical source.
# Run this whenever .shared/CANONICAL_INSTRUCTIONS.md changes.

set -e

CANONICAL=".shared/CANONICAL_INSTRUCTIONS.md"
CLAUDE_INSTRUCTIONS=".claude/instructions.md"
OPENCODE_INSTRUCTIONS=".opencode/instructions.md"
OPENAI_PROMPT="openai-system-prompt.txt"

if [ ! -f "$CANONICAL" ]; then
  echo "Error: $CANONICAL not found" >&2
  exit 1
fi

echo "Syncing instructions from $CANONICAL ..."

# Generate .claude/instructions.md
cat > "$CLAUDE_INSTRUCTIONS" << 'HEADER'
# Claude Agent Instructions

> Auto-generated from `.shared/CANONICAL_INSTRUCTIONS.md`
> Run `./scripts/sync-instructions.sh` to regenerate.
> Do not edit this file directly.

---

See `.shared/CANONICAL_INSTRUCTIONS.md` for full instructions.
This file adds Claude Code-specific context.

## Before You Code

- [ ] Read `.shared/context/CONTEXT.md`
- [ ] Read `.shared/context/TODO.md`
- [ ] Check relevant skill docs in `.shared/skills/`
- [ ] Run `npm test` to confirm green baseline

## After You Code

- [ ] `npm test` — all tests pass
- [ ] `npm run lint` — no errors
- [ ] `npm run build` — no type errors
- [ ] Update `.shared/context/CONTEXT.md`
- [ ] Run `./scripts/handoff.sh` if switching agents

HEADER

echo "Generated: $CLAUDE_INSTRUCTIONS"

# Generate .opencode/instructions.md
cat > "$OPENCODE_INSTRUCTIONS" << 'HEADER'
# OpenCode Agent Instructions

> Auto-generated from `.shared/CANONICAL_INSTRUCTIONS.md`
> Run `./scripts/sync-instructions.sh` to regenerate.
> Do not edit this file directly.

---

See `.shared/CANONICAL_INSTRUCTIONS.md` for full instructions.

Note: OpenCode does not support MCP. Use direct tool calls for external integrations.

## Before You Code

- [ ] Read `.shared/context/CONTEXT.md`
- [ ] Read `.shared/context/TODO.md`
- [ ] Check relevant skill docs in `.shared/skills/`

## After You Code

- [ ] `npm test` — all tests pass
- [ ] `npm run lint` — no errors
- [ ] `npm run build` — no type errors
- [ ] Update `.shared/context/CONTEXT.md`

HEADER

echo "Generated: $OPENCODE_INSTRUCTIONS"

# Generate openai-system-prompt.txt
cat > "$OPENAI_PROMPT" << 'HEADER'
# System Prompt — Auto-generated from .shared/CANONICAL_INSTRUCTIONS.md
# Run ./scripts/sync-instructions.sh to regenerate.
# For use with OpenAI Codex or similar API integrations.

HEADER

cat "$CANONICAL" >> "$OPENAI_PROMPT"
echo "Generated: $OPENAI_PROMPT"

echo ""
echo "Sync complete. Files updated:"
echo "  $CLAUDE_INSTRUCTIONS"
echo "  $OPENCODE_INSTRUCTIONS"
echo "  $OPENAI_PROMPT"
